### ISSUE TITLE
Your live link is not working it's redirecting on some another page.

### ISSUE THREAD

**Issue by Suraj-kumar00** [apoorvdwi/Portfolio#4]
It's redirecting to this page:
![Screenshot from 2024-04-15 15-53-23](https://github.com/apoorvdwi/Portfolio/assets/123288511/23b88d3a-46bd-4c71-83f4-ebffad8f50be)

**Comment by apoorvdwi** [comment]
Hey, I did not update the link here 
Try now, it should work
